name = "d1-proxy-service"  # 符合规范的worker名称
main = "index.js"
compatibility_date = "2024-08-01"

# D1数据库绑定配置
[[d1_databases]]
binding = "db"  # 与代码中的env.db对应
database_name = "m"  # 替换为你的数据库名称
database_id = "c1bf7d54-6457-498d-a6b2-289503bd94f2"  # 替换为你的数据库ID
    
